Add possibility to start tracking of a series via comment
LiquidFun/GeoStackr pull request #1
Opened 2021-03-11 19:45 UTC by Soulofdestiny

2021-03-11 21:22 UTC, LiquidFun requested changes
Looks good! Added a couple minor comments about formatting and some future goals for the project

2021-03-11 21:22 UTC, LiquidFun commented on geostackr.py
> +            print("series " + name + " by " + author + " has been added")
Consider using f-strings instead (Python 3.6+):

`print("series " + name + " by " + author + " has been added")`

becomes

`print(f"series {name} by {author} has been added")` inside the {} are expressions and you can do formatting

2021-03-11 21:22 UTC, LiquidFun commented on geostackr.py
> +            for topLevelComment in submission.comments:
Please use snake case as in the rest of the project (`top_level_comment`). I've changed my style from the last project, as this is what PEP 8 specifies for Python

2021-03-11 21:22 UTC, LiquidFun commented on geostackr.py
> +        series_name = format_title_to_tracking_title(submission.title)
In the last bot I tried automatically extracting the title, but I believe since then that this doesn't work. For example a lot of series would look like this `[2] Islands Challenge - Beautiful Caribbean Isles` (hypothetical title), so I added a rule for the bot to remove everything after a `-`, but then every series starting with `Non-moving` would match to `non`. 

I think this is a non trivial issue, so in the long run I think we should go for requiring the user to enter their series title. Then we only have to do this: 

```python
if format_title(title_entered_by_user) in format_title(title_of_current_submission):
    # code
```

2021-03-11 21:22 UTC, LiquidFun commented on geostackr.py
> +    tracked_series=[]
List comprehension could be a lot shorter:
```python
return [series['title'] for series in SERIES_CONFIGS]
```

2021-03-11 21:22 UTC, LiquidFun commented on series.yaml.example
> +### The series (plural) you want to be tracked
Repeated line

2021-03-11 21:22 UTC, LiquidFun commented on geostackr.py
> +def add_new_series_to_yaml(name, author, regex):
Consider using typing in parameters: `name: str`, etc.

2021-03-11 21:22 UTC, LiquidFun commented on geostackr.py
> +    subreddit = reddit.subreddit('soulofdestiny')
Good idea! Should probably add this to the `config.yaml` so different subs can be used for testing

2021-03-12 08:18 UTC, Soulofdestiny commented on geostackr.py
> +        series_name = format_title_to_tracking_title(submission.title)
yes, this is something I have also thought about - and for further visualization it makes sense anyway to store both, the real, beautiful name and some tracking-id

2021-03-12 08:18 UTC, Soulofdestiny commented
thanks for your comments, have adressed most of them.
need to go back to work now =)

2021-03-12 20:53 UTC, merged